### ISSUE TITLE
Failing uninstall() and reinstall()

### ISSUE THREAD

**Issue by mdilena** [mottosso/apiundo#2] opened 2018-05-20 21:34 UTC
#1 

There is an issue when uninstalling the module, where `__file__` in python 2.7 returns the .pyc and maya tries to unload that instead of apiundo.py, resulting in a non-existent plugin warning.
Also, when calling apiundo.py from a custom package hierarchy, the `__import__ `method will try to import the root package only, instead of the full import path (i.e. mypackage.subpackage.apiundo), resulting in an error when calling the install method from a wrong module.

**Comment by mottosso** [comment] 2018-07-19 07:05
Thanks for reporting this, sorry for the delay; wasn't receiving notifications, but are now.

Any thoughts on what could be the cause?

**Comment by mottosso** [comment] 2018-07-19 07:08
Just saw there was an [accompanying PR](https://github.com/mottosso/apiundo/pull/1) for this, thanks a bunch, merged!

**Closed as completed by mottosso** 2018-07-19 07:08 UTC
Labels: bug
